# Generated by Django 4.2.5 on 2025-01-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialization",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="trainerprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="trainerprofile",
            name="phone_number",
            field=models.CharField(default="0000000000", max_length=15),
        ),
    ]
