# Generated by Django 4.2.5 on 2025-01-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_app", "0002_alter_specialization_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainerprofile",
            name="experience",
            field=models.PositiveIntegerField(
                default=0, help_text="Years of experience"
            ),
        ),
        migrations.AlterField(
            model_name="trainerprofile",
            name="phone_number",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
