# Generated by Django 4.2.5 on 2025-01-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_app", "0003_alter_trainerprofile_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainerprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="trainer_profiles/"
            ),
        ),
    ]
