# Generated by Django 4.2.5 on 2025-01-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_app", "0004_trainerprofile_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainerprofile",
            name="description",
        ),
        migrations.AlterField(
            model_name="trainerprofile",
            name="available_time_slots",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="trainerprofile",
            name="experience",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="trainerprofile",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
