# Generated by Django 4.2.5 on 2025-01-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_app", "0009_packageenrollment_payment_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="packageenrollment",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="packageenrollment",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="packageenrollment",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
