# Generated by Django 4.2.5 on 2025-01-20 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gym_app", "0010_packageenrollment_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialization",
            options={
                "ordering": ["name"],
                "verbose_name": "Specialization",
                "verbose_name_plural": "Specializations",
            },
        ),
        migrations.AddField(
            model_name="specialization",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="specialization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
