# Generated by Django 5.1.4 on 2025-01-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_app", "0012_alter_specialization_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
