# Generated by Django 5.1.4 on 2025-01-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gym_app", "0015_remove_specialization_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialization",
            name="updated_at",
        ),
    ]
