# Generated by Django 5.1.4 on 2025-01-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0016_remove_specialization_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='updated_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='updated_at',
        ),
    ]
