# Generated by Django 5.1.4 on 2025-02-03 07:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_app", "0017_auto_20250120_1528"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_verification_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
