# Generated by Django 5.1.4 on 2025-02-03 08:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_app", "0018_customuser_email_verification_sent_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email_verification_token",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
    ]
